### ISSUE TITLE
Why was I removed from the foundation for participating in a nodejs/moderation discussion?

### ISSUE THREAD

**Issue by joshmanders** [nodejs/inclusivity#137]
I was giving my opinion regarding a moderation discussion about an action that happened 2 months ago, and I get an email from GitHub saying I was removed from the organization.

What was the reasoning for this?

**Comment by mikeal** [comment]
I removed you.

I created an issue regarding you and it wouldn't have been appropriate for you to be commenting on it.

You aren't a committer in any of the projects which is usually how you get membership. If you were a committer anywhere I would have left that and just removed you from the members team which would have removed you from the moderation repo but because you were only in the members team removing from the org was more prudent.

**Comment by joshmanders** [comment]
Created an issue regarding me? What did I do?

**Comment by mikeal** [comment]
People are concerned that some of your recent activity is a form of harassment so I put in a request monitor your activity.

**Comment by joshmanders** [comment]
And who exactly did I harass? Because from what I have tried to get taken care of was against Ashley and Emily Rose harassing me.

**Comment by nebrius** [comment]
@joshmanders this is a public repo, and is not the place to be discussing this. I strongly recommend you take some time to cool your head before discussing this further.

**Comment by mikeal** [comment]
I've put a link to this issue in the moderation issue so that people there are aware of your response here.

You still have access to participate in every repo in the project that is not part of the internal moderation system for project committers.

**Comment by Fishrock123** [comment]
The OP scrubbed their own comments here. I am going to lock this issue.

**Comment by ashleygwilliams** [comment]
i printed them for posterity. will add to the moderation thread.
