### ISSUE TITLE
IRC Moderation Policy

### ISSUE THREAD

**Issue by nebrius** [nodejs/inclusivity#138]
## Purpose

To draft a proposal for an IRC moderation policy. The Node.js IRC channel is considered an official communication of the Node.js project, and so the Code of Conduct for Node.js applies there. The current [moderation policy](https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md) is specific to GitHub interactions, leaving the IRC channel in a bit of a gray area.

We should create a moderation policy that is tailored for IRC and takes into account the way IRC is used and what moderation abilities IRC provides. This policy will ultimately live under [the TSC repository](https://github.com/nodejs/TSC).
## Focus

This issue is specific to the moderation policy for IRC, not GitHub or other communication mediums. This issue is also about crafting policy. It may be helpful to discuss specific incidents, but we should take care to only discuss incidents that occurred on IRC and to make sure we don't discuss any confidential or sensitive information.

Some off topic examples include, but are not limited to:
- The moderation policy for GitHub, except where it applies or relates to IRC
- Past grievances, unless said grievances illustrate an aspect of the moderation policy _and_ they are discussed calmly and in accordance with the Inclusivity Working Group's [Code of Conduct](https://github.com/nodejs/inclusivity/blob/master/CODE_OF_CONDUCT.md)
  - This includes why you or someone else was banned
- Who will implement the policy, i.e. who the IRC admins and moderators will be

**Comment by Fishrock123** [comment]
Assigning since this ought to be my responsibility.

There is some previous art (which is what the irc channels point to at the current time), notably:
- http://nodeirc.info/ 
- isaac's "Policy on trolling" blog http://blog.izs.me/post/30036893703/policy-on-trolling
- "IRC OP Protips" https://gist.github.com/maxogden/8610086

This policy needs to specific to IRC as there are many nuances for IRC not found elsewhere.

An example would be *how* to ban people, since there are multiple ways of doing that.
Also, needs some guidelines on who OPs are and what the proper OP `+flags` are on freenode.

Another example, people sometimes need to be timed out (temp banned) if their connection is really bad, otherwise it will spam the channel with join/leave messages. This is very IRC specific.

**Comment by Fishrock123** [comment]
Ok uh, I'm probably not going to effectively get around to this for a while. I'm happy to give pointers to and answer any questions for anyone that wants to take it over though.

**Comment by Fishrock123** [comment]
even a rough draft would be useful, for get who is or isn't OPs for now.

**Comment by TheAlphaNerd** [comment]
I'm up for taking this over if you are cool with it @Fishrock123 I'll break some ground tomorrow

**Comment by Fishrock123** [comment]
Sure. My suggestion would be to take Isaac's trolling policy and work up from there, or, that was my plan anyways.

**Comment by TheAlphaNerd** [comment]
I can't assign this to myself as I'm not in the wg... but I submitted an application

**Comment by ivan-vilches** [comment]
Yes i was banned for say that moderator no need to be aggressive , Jeremiah Senkpiel send me this :

Please read though http://nodeirc.info/ -- the "official" rules for that channel are listed there.

Well , there is https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md
and 
http://confcodeofconduct.com/
