### ISSUE TITLE
Scope of WG Charter and CoC

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#38]
It's become clear that there's some incongruence in the understanding of the scope of the expected powers of this working group, both in its charter, and of its CoC.

The question to discuss is how far the charter will go, how enforcement will work, and which parts of that are exclusively within the scope of this WG, and which parts will simply be bubbled up through the Node Foundation's existing processes. We will also discuss the scope within which this WG is able to change and improve existing processes.

This discussion will (hopefully) be mainly a session for clarifying and documenting (for ourselves) how the Foundation's processes work, and what leeway we're expected to have in working here. @mikeal may be helpful as a resource here, either as a participant in the meeting, or as a source of information prior to the meeting that someone else can then convey, as communicating these processes is a large part of his role.

**Comment by mikeal** [comment]
I'll go specifically into the Code of Conduct.

This is the [current process](https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md#bootstrap-governance):

> Once the TC ratifies a charter the WG inherits the following documentation for governance, contribution, conduct and an MIT LICENSE. The WG is free to change these documents through their own governance process, hence the term "bootstrap."

Basically, the WG is expected to copy those documents and then modify them as necessary. The TSC is essentially saying "Here's some governance to get you started but you can modify these without our express consent."

In that regard this WG is free to write a new CoC and replace the one it would have copied over previously.

* **Open Issue 1:** This described the policy well for new working groups but several existing sub-projects were brought in under the CTC as part of the core project with their prior membership and governance intact. If they didn't have one of these documents, like a CoC, what is the behavior? That hasn't been answered yet.
* **Open Issue 2:** Most of the working groups have not copied these documents over, which is a sign this copy/paste process doesn't work. It would be my recommendation that some time in the near future the TSC/CTC modify this process to point to foundation wide bootstrap documents referenced in a README rather than explicit copy/paste.
* **Open Issue 3:** If WGs have the right to modify the CoC do they have the right to remove them entirely? That certainly wasn't the goal of the initial process but it is now a grey area since it was never explicitly stated.

So, there's no question that this WG has the right to define a CoC for *itself*. The TSC process for Top Level Projects and Working Groups only states that WGs are responsible for creating and modifying their processes [inline with three values](https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md#incubation) (Transparency, Participation, and Efficacy) and each process is a balance of those values not a combination of absolutes. If you somehow created a policy that was less transparent, effective, and discouraged participation the TSC could come down on it, especially prior to being chartered (or incubated if it's a Top Level Project). Also note that the policy would only cover moderation and possibly bans from *this* repository and not from the entire org.

I also think it would be a good goal for this group to state a future intent: that the goal of the CoC for the Inclusivity WG is to eventually be a recommendation for a new org-wide CoC (replacing the current Rust based one that is copy/pasted to new WGs). People seem to be making that assumption already so stating that while it does not **now** apply to the entire org the goal is that it will be in the future. But, keep in mind that while the TSC can change the template for new TLPs the CTC would then have to ratify changing the one in core and other WGs would need to do the same (although if this comes with a recommendation ratified by the TSC it's likely to be adopted).

**Comment by jasnell** [comment]
+1 thanks @mikeal for drawing that out. To make sure that things are clear... when I (as a TSC member) provide feedback on the code of conduct being considered for this WG, I am **NOT** doing so from the point of view, "I am a TSC Member, this is what you **must** do". Rather, I'm simply offering my personal input on what I personally feel is appropriate or necessary or what I think would have the greatest opportunity for success. It's still up to this WG to figure out for itself what Code of Conduct and Governance model it's going to have.

**Comment by zkat** [comment]
As discussed in the [meeting on 2015-11-24](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-11-24.md#scope-of-inclusivity-working-group-charter-and-coc---38), there is no expectation or intention by anyone in this WG's membership that Charter or CoC of this group being discussed extends its authority anywhere outside of the working group itself. Any enforcement beyond the scope of discussion internal to us is to be handled through the usual Node Foundation channels, and we're all clear on that. I'm this closing this issue.
