### ISSUE TITLE
Private/Public balance in discussions

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#40]
It has been a repeatedly-stated goal that this WG's output be public, and I think that, in itself, has been wholly uncontroversial.

That said, there is a discussed private component to this. Its existence, specific mechanics, and the role it would have if it would exist, as well as potential issues, should be discussed.

It would be hugely useful to have someone familiar with Foundation processes to help smooth this discussion out and provide useful strategies for addressing the various parties' concerns regarding this.

Update: As I mentioned in #37, please use the comments here to neutrally suggest agenda items. I will likely delete any comments that try to discuss the issue in any detail. If you participate in the meeting, or have a representative, you're free to have representation of your point. Sorry for the inconvenience.

**Comment by TheAlphaNerd** [comment]
The private / public binary is potentially problematic. A third option I can think of off hand is private to the public but open to collaborators (a group of 150 or so people involved with the project). 

Choosing this third option may prove a great comprise for certain modes of communication.

**Comment by 950c** [comment]
I find the idea of a secret hidden process to censor things immensely scary.

**Comment by juliepagano** [comment]
I think it would be helpful to have some specific discussion points around this to help with facilitation and keeping this discussion focused. 

My initial thoughts are we need answers to the following. Feel free to add on to this list, as I'm sure I'm forgetting something.

- What private spaces, if any, should the group have (e.g. should the slack channel stay private)?
- If the group has private spaces, who has access to them? How do we set appropriate guidelines for those spaces to maintain privacy?
- What types of discussions are likely to happen in private? Why is it valuable for them to happen in private?
- What processes and timelines should the group use to share the outcomes of private discussions publicly?

I don't think these all need to happen in the next meeting. Maybe we can pick a couple and spin off the others for future discussion?

**Comment by scottgonzalez** [comment]
> I will likely delete any comments that try to discuss the issue in any detail. If you participate in the meeting, or have a representative, you're free to have representation of your point.

I'm curious how this works. Are there any public discussion forums for this WG other than these issues and the meetings? So far I haven't become aware of any, and I can't join the meeting because I have a work meeting at the same time.

**Comment by nebrius** [comment]
Following up on this because we seem to have settled into a rhythm with the WG. Our communication channels are:

- GitHub issues, which are public
- Slack public channels, which anyone can join via the link at https://github.com/nodejs/inclusivity/#inclusivity-working-group
- Slack private channels (currently only used to discuss admissions, although this may change?)
- Typeform submissions for admission to this working group. The form is publicly accessible, but the results are confidential by design.

A few questions for everyone:

- Does the above list sound accurate?
- Does the above list achieve the desired public/private balance?
- Should the above list be formally documented somewhere?
- Do we have appropriate guidelines in place to maintain privacy, where applicable, and transparency, where applicable?

I hope the above will help us to decide if we feel this issue has been addressed or if we need to do some more work first.

**Comment by scottgonzalez** [comment]
In the interest of full disclosure, over the past three weeks (the time period that I have data for), only ~6.5% of Slack messages were in private channels. We really do limit the scope of private discussions as much as possible.

**Comment by nebrius** [comment]
This makes me think, I wonder if there's a way to automatically publish that report somewhere?

**Comment by scottgonzalez** [comment]
It doesn't look like there's any API method to get this data. I used the weekly summary emails that they send to calculate the percentage. I did just find an admin stats page that shows all time stats, which has private messages at 17% (presumably from before the rejuvenation of this group). There doesn't seem to be an automated way to pull this info though :-/
