### ISSUE TITLE
Moderation in the wider Node community

### ISSUE THREAD

**Issue by zkat** [nodejs/inclusivity#44]
We've discussed multiple times now that it may be within the scope of this WG to somehow flag things or propose moderation, in other parts of the Node community, including but not limited to: conferences, other WGs, the TSC, or even the board.

Let's discuss the way this functionality is granted to working groups, what our hard upper bounds are, and what our negotiable (and/or already-negotiated) bounds are for moderation.

We can talk about the existence of a separate moderation WG/repo here, and how that would interoperate with this WG's output, cross-membership, etc.

**Comment by juliepagano** [comment]
This was discussed in [2015-12-18](https://github.com/nodejs/inclusivity/blob/master/meetings/2015-12-18.md). We agreed that it would be beneficial to write up an early straw-proposal, so that we would have a discussion point to work from in a future meeting. Created #66 to track assignment of that task.

**Comment by nebrius** [comment]
Do we think that #132 includes the concerns in this issue, and if so can we close this one?

**Comment by nebrius** [comment]
Closing in favor of #132, feel free to reopen if need be.
