### ISSUE TITLE
Draft Proposal: Rotating Meeting Time

### ISSUE THREAD

**Issue by Trott** [nodejs/inclusivity#74]
In an effort to be inclusive internationally, it may be good to rotate the time of the recurring meeting.

I would propose that we start with the time of the last two meetings (10 AM Pacific Time, day of week TBD as we'd been doing Friday but that is Saturday in some parts of the world and that may or may not be a good scheduling day).

We can shift that time by 8 hours to have three different meeting times. I don't know if it makes sense to switch the time every meeting, or stay on one time for two or three meetings before rotating.

Important note: The times will shift around as daylight savings time happens at different dates (or not at all) in different places. Daylight savings shifts in the opposite direction in the Northern and Southern Hemispheres, so the time slipperiness may be as much as two hours at points!

Here's how this proposal (which I fully expect to get discussed a lot and modified and rejected before being embraced and rejected a second time and...) looks today with time zones ordered starting with my own and moving east:

| San Francisco | New York | Frankfurt | Chennai | Seoul/Tokyo |
| --- | --- | --- | --- | --- |
| 10:00 AM | 1:00 PM | 7:00 PM | 11:30 PM | 3:00 AM |
| 6:00 PM | 9:00 PM | 3:00 AM | 7:30 AM | 11:00 AM |
| 2:00 AM | 5:00 AM | 11:00 AM | 3:30 PM | 7:00 PM |

I'm honestly not sure how workable this can be made, but let's have the discussion.

We also need to figure out what the times would be tied to. When the U.S. goes to Daylight Savings Time, do the times for SF and NY change in the table above, or do the other times change by one hour (assuming those locations do not enter/leave daylight savings time at the same time)?

**Comment by ashleygwilliams** [comment]
fwiw the EST times really only have one good one, while the others both have 2 (criteria: 6am-8pm, i.e. slightly longer than general work hours)

thoughts?

**Comment by Charlotteis** [comment]
For the UK (GMT) it would be:

2:00 AM
10:00 AM
6:00 PM

In general I think this is a good idea. My only concern is that the size of the groups attending the meetings (at this stage) might be significantly smaller because of the rotation, but it also means more people in general will be able to get involved which is a very good thing.

Anecdata on the UK times and things for _me personally_. If done on a Friday I would not be able to attend any of these times. Well, I'd only be able to physically attend the 10AM but with a full time job I'm not sure how takin an hour out to do not-work things would work. But if that is the set day and I'm welcome to join a meeting, I could try (though often would not succeed). Weekends are infinitely better for me, but I also don't want to force people to work weekends :)

As for regularity of rotation, how about every 2+ meetings? That way if people who didn't get to finish their discussions on meeting one, they can finish it up on meeting 2. And I think it gives a little more room for people to co-ordinate times etc rather than have to think about it's rotation every week :)

**Comment by Trott** [comment]
One thing that I was reminded of in the first Testing WG meeting we had yesterday: A lot (most?) working groups don't meet every week. Some don't meet at all and coordinate entirely on GitHub and/or IRC or whatever. But the ones that *do* meet will often have a meeting every other week, every three weeks, once a month...

**Comment by ashleygwilliams** [comment]
i dont think we are planning on every week-- every 2 weeks was my recommendation. unless i'm forgetting something? thoughts?

**Comment by nebrius** [comment]
I seem to recall every 2 weeks as well. Even if it wasn't, I say +1 on every two weeks. It feels like a good cadence to me, and we seem to be making good headway in general right now, so we must be doing something right :)

**Comment by sup** [comment]
if we have a critical issue, we can still do an emergency meeting with one of the times on here.

also, in regards to weekdays, anyone have plans yet? i'm free for everything but thursdays
